JNG-4377 Move PSM generator into judo-meta-psm.
BlackBeltTechnology/judo-meta-psm pull request #155
Opened 2023-01-13 12:32 UTC by robertcsakany

2023-01-16 22:42 UTC, bencegelei approved these changes
I will just believe that actual moving happened here:D

2023-01-18 09:23 UTC, gaborflorian approved these changes

2023-01-18 09:39 UTC, gaborflorian approved these changes

2023-01-18 14:12 UTC, gaborflorian commented on generator-maven-plugin/README.adoc
> +<4> Project type. It is used to resolve the project descriptor yaml files. The yaml file name is `<project type>-project.yam;`.
`<project type>-project.yam;` -> `<project type>-project.yaml;` ?

2023-01-18 14:15 UTC, gaborflorian requested changes

2023-01-18 14:15 UTC, gaborflorian commented on generator-maven-plugin/README.adoc
> +<4> Project type. It is used to resolve the project descriptor yaml files. The yaml file name is `<project type>-project.yam;`.
<project type>-project.yam; -> <project type>-project.yaml; ?

2023-01-18 14:32 UTC, noherczeg requested changes

2023-01-18 14:32 UTC, noherczeg commented on generator-engine/.project
> +	<name>judo-tatami-ui2flutter</name>
ui2flutter?

2023-01-18 14:50 UTC, noherczeg requested changes

2023-01-18 14:50 UTC, noherczeg commented on generator-engine/src/main/java/hu/blackbelt/judo/meta/psm/generator/engine/PsmGenerator.java
> +    public static final Boolean CLIENT_TEMPLATE_DEBUG = System.getProperty("clientTemplateDebug") != null;
client template?

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +            <groupId>hu.blackbelt.judo.meta</groupId>
We should add comments / notes stating that these dependencies are just example models for testing.

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +<9> Actors used to generation. When it is not set all actors are generated. To define use coma separated fully qualified name of actor class.
"used for generation"

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +Recommended to store the context in ThreadLocal, because
"Our recommendation is to store"...

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +the `actorType` variables is defined.
"variable"

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +objects which is used as root context for the given handlebar template. (`templateName`)
which are used

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +<5> Path expression return with a path where the generated file is placed.
returns

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +the generation have to ignore the given file to keep the edited version. To achieve this
"generator has to ignore"

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +There is two template. First one is the 'base`, second one is the `overrrid`.
There are two templates.

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +There is two template. First one is the 'base`, second one is the `overrrid`.
Did we mean "override"?

2023-01-18 14:50 UTC, noherczeg commented on generator-maven-plugin/README.adoc
> +off the original definition is replaced to the `override` version. When a
"definitions are replaced with the"

2023-01-18 21:03 UTC, bencegelei approved these changes

2023-01-18 21:54 UTC, noherczeg approved these changes

2023-01-19 07:30 UTC, merged