JNG-4503 Release judo meta psm
BlackBeltTechnology/judo-meta-psm pull request #165
Opened 2023-02-28 13:57 UTC by gaborflorian

2023-02-28 14:55 UTC, noherczeg approved these changes

2023-02-28 21:43 UTC, bencegelei requested changes

2023-02-28 21:43 UTC, bencegelei commented on pom.xml
> +                <version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 10:09 UTC, robertcsakany approved these changes

2023-03-01 11:54 UTC, bencegelei approved these changes

2023-03-09 10:24 UTC, merged